[project]
name = "mcp-claude-code"
version = "0.1.1"
description = "MCP implementation of Claude Code capabilities"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp>=1.3.0",
    "httpx>=0.27",
    "uvicorn>=0.23.1",
    "pynvim>=0.5.2",
]

[project.scripts]
claudecode = "mcp_claude_code.cli:main"

[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["mcp_claude_code"]
